### ISSUE TITLE
load.properties parameter should load from jar resources

### ISSUE THREAD

**Issue by SentryMan** [avaje/avaje-config#38]
I want to be able to load env specific props based on profile. Say I have an application properties file like this
 ```
some.common.prop=true
load.properties=src/main/resources/application-${profile:local}.properties
```
In the current state, files are only supported, so when I upload my jar to my server it doesn't pull the props because there is no such folder.

I'd like something like this to work as well as standard path based config
 ```
some.common.prop=true
load.properties=application-${profile:local}.properties
```

**Comment by SentryMan** [comment]
it seems that 2.4 is still not available on mvn central.

**Comment by rbygrave** [comment]
Yes, it didn't get released from staging (my bad) - I've done that now. I'll change it to auto-release from staging.

**Comment by SentryMan** [comment]
It's still not available.

**Comment by rbygrave** [comment]
It looks to be there?? -
https://repo1.maven.org/maven2/io/avaje/avaje-config/2.4/

**Comment by SentryMan** [comment]
yeah it's good now
