### ISSUE TITLE
Change from System.Logger to use events and control how those events are logged.

### ISSUE THREAD

**Issue by rbygrave** [avaje/avaje-config#47]
> What our config framework provides is a simple event system. When logging is done you can drain the queue of events usually replaying them to logging our System.err.

The reason for doing this is because sometimes we want the configuration to load completely BEFORE any logging is used. This allows the configuration to put things into System Properties which is used to configure the actual logging.

**Comment by SentryMan** [comment]
> use events

so the first thing that comes to mind is to take the logs we output and keep them in a List<String> somewhere. From there we could provide a method for users to log themselves. Am I on the right track?

**Comment by rbygrave** [comment]
Yes, well an "event" is something like a System.Logger.LEVEL + message (+ maybe a code if we want some business logic to work off codes rather than message content).
